### Piowave code implementations

### Path settings
path:
  expname: raf_test
  dataset_type: RAF
  logdir: logs/RAF_Empty/


### rendering settings
render:
  xyz_min: -12
  xyz_max: 12
  near: 0
  far: 6
  n_samples: 32
  n_azi: 48
  n_ele: 24
  speed: 346.8
  fs: 16000
  pathloss: 0.5
  sig_length: 1600

### training settings
train:
  lr: 2e-4
  weight_decay: 0 
  T_max: 300000
  eta_min: 8e-5
  load_ckpt: False
  val_freq: 10000
  save_freq: 10000
  total_iterations: 80000

  spec_loss_weight: 1
  amplitude_loss_weight: 1
  angle_loss_weight: 1
  time_loss_weight: 20
  energy_loss_weight: 3
  multistft_loss_weight: 2

### model settings  
model: 
  signal_output_dim: 1600
  leaky_relu: 0.03

  pos_encoding_sigma:
    base_resolution: 16
    log2_hashmap_size: 18
    n_features_per_level: 2
    n_levels: 20
    otype: HashGrid

  pos_encoding_sig:
    base_resolution: 16
    log2_hashmap_size: 18
    n_features_per_level: 2
    n_levels: 20
    otype: HashGrid

  dir_encoding_sig:
    base_resolution: 16
    log2_hashmap_size: 18
    n_features_per_level: 2
    n_levels: 20
    otype: HashGrid
  
  tx_pos_encoding_sigma:
    base_resolution: 16
    log2_hashmap_size: 18
    n_features_per_level: 2
    n_levels: 20
    otype: HashGrid
  
  tx_pos_encoding_sig:
    base_resolution: 16
    log2_hashmap_size: 18
    n_features_per_level: 2
    n_levels: 20
    otype: HashGrid

  tx_dir_encoding_sig:  
    base_resolution: 16
    log2_hashmap_size: 18
    n_features_per_level: 2
    n_levels: 20
    otype: HashGrid

  sigma_encoder_network:
    activation: ReLU
    n_hidden_layers: 3
    n_neurons: 128
    otype: FullyFusedMLP
    output_activation: None

  sigma_decoder_network:
    activation: ReLU
    n_hidden_layers: 1
    n_neurons: 128
    otype: FullyFusedMLP
    output_activation: None

  signal_network:
    activation: ReLU
    n_hidden_layers: 4
    n_neurons: 512
    otype: CutlassMLP
    output_activation: None
